version: "3.7"

services:
  oathkeeper:
    build:
      context: .
      dockerfile: Dockerfile-dc
    ports:
      - "4455:4455"
      - "4456:4456"
    command: serve --config=/etc/config/oathkeeper/config.yaml
    environment:
      - TRACING_PROVIDER=jaeger
      - TRACING_PROVIDER_JAEGER_SAMPLING_SERVER_URL=http://jaeger:5778/sampling
      - TRACING_PROVIDER_JAEGER_LOCAL_AGENT_ADDRESS=jaeger:6831
      - TRACING_PROVIDER_JAEGER_SAMPLING_TYPE=const
      - TRACING_PROVIDER_JAEGER_SAMPLING_VALUE=1
    volumes:
      - type: bind
        source: ./.docker_compose
        target: /etc/config/oathkeeper
    restart: on-failure
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686" # The UI port
#      These are ports for collecting, sampling, agents, ...
#      - "5775:5775/udp"
#      - "6831:6831/udp"
#      - "6832:6832/udp"
#      - "5778:5778"
#      - "14268:14268"
#      - "9411:9411"
